version: "3.9"
services:
  db:
    container_name: db
    image: postgres:13.2
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${POSTGRES_PORT}:5432
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_LISTEN_PORT
    links:
      - db:pgsql-server
    ports:
      - ${PG_ADMIN_PORT}:80
  cms:
    container_name: cms
    image: strapi/strapi
    depends_on:
      - db
    environment:
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_HOST
      - DATABASE_SSL
    links:
      - db:pgsql-server
    ports:
      - ${PORT}:1337
    volumes:
      - C:\ProgStudy\js-practics\blog\packages\backend:/srv/app

